<a href="https://colab.research.google.com/github/Manojkumaar96/Task-2/blob/main/Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
N = np.zeros(10)
print(N)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
N = np.zeros((10,10))
print("%d bytes" % (N.size * N.itemsize))

800 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
N = np.zeros(10)
N[4] = 1
print(N)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
N = np.arange(10,50)
print(N)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
N = np.arange(50)
N = N[::-1]
print(N)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
N = np.arange(9).reshape(3,3)
print(N)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
N = np.nonzero([1,2,0,0,4,0])
print(N)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
N = np.eye(3)
print(N)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
N = np.random.random((3,3,3))
print(N)

[[[0.77791835 0.17787317 0.48532472]
  [0.35759934 0.6422781  0.42988564]
  [0.94439772 0.28088395 0.86168289]]

 [[0.35567559 0.91742265 0.02032527]
  [0.12040389 0.60472264 0.93533946]
  [0.37783974 0.91547496 0.64273418]]

 [[0.68808344 0.68192876 0.91038653]
  [0.84646888 0.65005794 0.10231161]
  [0.34650952 0.35231505 0.73293763]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
N = np.random.random((10,10))
Nmin, Nmax = N.min(), N.max()
print(Nmin, Nmax)

0.006275905293989581 0.9985766276014334


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
N = np.random.random(30)
a = N.mean()
print(a)

0.49334176718681405


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
N = np.ones((10,10))
N[1:-1,1:-1] = 0
print(N)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
N = np.ones((5,5))
N = np.pad(N, pad_width=1, mode='constant', constant_values=0)
print(N)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
N = np.diag(1+np.arange(4),k=-1)
print(N)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
N = np.zeros((8,8),dtype=int)
N[1::2,::2] = 1
N[::2,1::2] = 1
print(N)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
N = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(N)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
N = np.random.random((5,5))
Nmax, Nmin = N.max(), N.min()
N = (N - Nmin)/(Nmax - Nmin)
print(N)

[[0.86032397 0.15258195 0.17758394 0.92907624 0.91496946]
 [0.46724214 0.71459214 0.26141397 0.54133029 0.92080985]
 [0.60763055 0.91623721 0.79334862 0.4268865  0.5463632 ]
 [0.         0.67568667 0.62293023 0.91599086 0.19968669]
 [0.7614534  0.28451531 0.4051839  1.         0.04626758]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
N = np.dot(np.ones((5,3)), np.ones((3,2)))
print(N)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
N = np.arange(11)
N[(3 < N) & (N <= 8)] *= -1
print(N)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

NameError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
N = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(N)), N))

[  3.   1.   8.   4.  -3. -10.   8.  -1.   8.  -6.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
N1 = np.random.randint(0,10,10)
N2 = np.random.randint(0,10,10)
print(np.intersect1d(N1,N2))

[0 1 5 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
_ = np.seterr(**defaults)
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
N = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(N)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
N = np.random.uniform(0,10,10)

print (N - N%1)
print (np.floor(N))
print (np.ceil(N)-1)
print (N.astype(int))
print (np.trunc(N))

[1. 7. 9. 9. 1. 9. 6. 8. 6. 3.]
[1. 7. 9. 9. 1. 9. 6. 8. 6. 3.]
[1. 7. 9. 9. 1. 9. 6. 8. 6. 3.]
[1 7 9 9 1 9 6 8 6 3]
[1. 7. 9. 9. 1. 9. 6. 8. 6. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
N = np.zeros((5,5))
N += np.arange(5)
print(N)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate():
    for i in range(10):
        yield i
N = np.fromiter(generate(),dtype=float,count=-1)
print(N)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
N = np.linspace(0,1,11,endpoint=False)[1:]
print(N)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
N = np.random.random(10)
N.sort()
print(N)

[0.30773743 0.4562242  0.45942154 0.50612752 0.59495394 0.62411256
 0.72436721 0.8717333  0.91303529 0.99549883]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
N = np.arange(10)
np.add.reduce(N)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
N = np.zeros(10)
N.flags.writeable = False
N[0] = 1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
N = np.random.random((10,2))
X,Y = N[:,0], N[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.27451473 0.82845746 0.30838608 1.08499674 1.26672273 0.86319211
 1.31703425 0.39860224 0.96424813 1.34897591]
[1.00290904 0.50171348 1.42842216 0.92467149 0.70509239 0.29338945
 0.7487594  1.25160794 0.09778227 0.82253131]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
N = np.random.random(10)
N[N.argmax()] = 0
print(N)

[0.89146534 0.40784334 0.68666067 0.19243058 0.         0.8406994
 0.61939324 0.48044742 0.47411575 0.31157216]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
N = np.zeros((5,5), [('x',float),('y',float)])
N['x'], N['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(N)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
A = np.arange(8)
B = A + 0.5
C = 1.0 / np.subtract.outer(A, B)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(threshold=np.nan)
N = np.zeros((16,16))
print(N)

ValueError: ignored

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

97


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
N = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(N)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
import scipy
import scipy.spatial
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.32570957 0.86858905 0.572388   0.18729403 0.89556423
  0.90604884 0.29746947 0.60910417 0.26144808]
 [0.32570957 0.         0.70658575 0.33147268 0.23711614 0.66791828
  0.58835533 0.07734525 0.35430954 0.30343158]
 [0.86858905 0.70658575 0.         0.38904971 0.6820124  0.19676019
  0.89516836 0.65607329 0.95100779 0.99423145]
 [0.572388   0.33147268 0.38904971 0.         0.39594596 0.33796809
  0.59433671 0.29913846 0.56770458 0.63253774]
 [0.18729403 0.23711614 0.6820124  0.39594596 0.         0.71071309
  0.8165181  0.17229761 0.5841918  0.36330511]
 [0.89556423 0.66791828 0.19676019 0.33796809 0.71071309 0.
  0.73076207 0.6364827  0.84639033 0.97020467]
 [0.90604884 0.58835533 0.89516836 0.59433671 0.8165181  0.73076207
  0.         0.64428206 0.37240144 0.76823813]
 [0.29746947 0.07734525 0.65607329 0.29913846 0.17229761 0.6364827
  0.64428206 0.         0.43082938 0.33898265]
 [0.60910417 0.35430954 0.95100779 0.56770458 0.5841918  0.84639033
  0.37240144 0.430829

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
N = np.arange(10, dtype=np.float32)
N = N.astype(np.int32, copy=False)
print(N)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
N = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(N):
    print(index, value)
for index in np.ndindex(N.shape):
    print(index, N[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
a = 10
b = 3
N = np.zeros((a,a))
np.put(N, np.random.choice(range(a*a), b, replace=False),1)
print(N)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[-0.13554759  0.44350751 -0.11856677 -0.01138279  0.25111258  0.14124117
  -0.40946704  0.00890253  0.1963506  -0.3661502 ]
 [-0.49617699 -0.6273275   0.02073372  0.08609159  0.09928854 -0.08469325
   0.34741412  0.30624964  0.1363198   0.21210031]
 [-0.07361085 -0.20018902  0.09206741  0.33096425  0.33243792  0.29876134
   0.07944338 -0.24204257 -0.09296032 -0.52487155]
 [ 0.50586823  0.45956546  0.44414387 -0.3294298  -0.1650632  -0.09845276
  -0.27142713 -0.12800229 -0.33770886 -0.07949351]
 [ 0.17693481  0.2266083   0.20763059 -0.2072335  -0.55802675 -0.20899153
   0.19523459  0.23199623 -0.15225934  0.0881066 ]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
N = np.random.randint(0,10,(3,3))
print(N)
print(N[N[:,1].argsort()])

[[9 4 3]
 [2 8 5]
 [4 8 2]]
[[9 4 3]
 [2 8 5]
 [4 8 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
N = np.random.randint(0,3,(3,10))
print((~N.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.41773881926743817


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

N = NamedArray(np.arange(10), "range_10")
print (N.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
N = np.ones(10)
I = np.random.randint(0,len(N),20)
N += np.bincount(I, minlength=len(N))
print(N)
np.add.at(N, I, 1)
print(N)

[2. 2. 1. 5. 3. 4. 5. 4. 2. 2.]
[3. 3. 1. 9. 5. 7. 9. 7. 3. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
A = [1,2,3,4,5,6]
B = [1,3,9,3,4,1]
Z = np.bincount(B,A)
print(Z)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w,h = 16,16
A = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
B = A[...,0]*(256*256) + A[...,1]*256 +A[...,2]
Z = len(np.unique(B))
print(Z)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[51 67 63 53]
 [54 45 50 57]
 [58 62 58 44]]
[[51 67 63 53]
 [54 45 50 57]
 [58 62 58 44]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
import pandas as pd
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
print(pd.Series(D).groupby(S).mean())

[0.37242031 0.47047617 0.53182633 0.50972179 0.37968028 0.34933396
 0.50675418 0.18507103 0.46255492 0.52838226]
0    0.372420
1    0.470476
2    0.531826
3    0.509722
4    0.379680
5    0.349334
6    0.506754
7    0.185071
8    0.462555
9    0.528382
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))  
np.diag(np.dot(A, B))
np.sum(A * B.T, axis=1)
np.einsum("ij,ji->i", A, B)

array([1.48971367, 1.27039147, 0.93704408, 1.37353414, 0.4953583 ])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
A = np.array([1,2,3,4,5])
nz = 3
B = np.zeros(len(A) + (len(A)-1)*(nz))
B[::nz+1] = A
print(B)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 24) ( 0, 25) ( 1, 92) ( 1, 98) ( 8, 35) ( 8, 90) (13, 37) (13, 40)
 (16, 17) (16, 19) (16, 22) (16, 40) (16, 47) (16, 54) (17, 19) (22, 54)
 (22, 81) (22, 95) (24, 25) (28, 67) (28, 88) (35, 90) (37, 40) (40, 47)
 (60, 71) (60, 83) (67, 88) (71, 83) (81, 95) (92, 98)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
A = np.bincount([1,1,2,3,4,4,6])
B = np.repeat(np.arange(len(A)), A)
print(B)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
N = np.arange(20)
print(moving_average(N, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
N = rolling(np.arange(10), 3)
print(N)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
N = np.random.randint(0,2,100)
np.logical_not(N, out=N)

N = np.random.uniform(-1.0,1.0,100)
np.negative(N, out=N)

array([ 0.84733324, -0.31697751, -0.88803722, -0.80926427, -0.70838061,
       -0.35778049, -0.58489636, -0.84535923, -0.25486973,  0.81883943,
        0.30971844, -0.95797077, -0.61305856,  0.30015635,  0.79287422,
        0.73164621, -0.7056732 ,  0.37373045,  0.51553613,  0.42285459,
        0.15747574, -0.56765298,  0.93335123,  0.56353275,  0.25196474,
       -0.59036016,  0.42698945,  0.2575049 ,  0.54096129,  0.05267409,
       -0.56667083, -0.0356087 , -0.87581756, -0.72413992, -0.64953655,
       -0.62712571,  0.92450987, -0.7194962 , -0.41079043,  0.33600044,
        0.72193828, -0.39848134, -0.2237735 ,  0.96384315,  0.17970232,
        0.66532677, -0.41774957,  0.6764852 , -0.47360779,  0.5796586 ,
       -0.51780462, -0.82268314,  0.71924913,  0.61242382,  0.65194629,
        0.91326084,  0.59804461,  0.19220574, -0.26092265, -0.05948529,
        0.11194385, -0.93388096,  0.3120986 ,  0.78008373, -0.13181942,
       -0.60765728,  0.19388373,  0.81700997, -0.43849285,  0.73

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(A, B, C):
    T = B - A
    L = (T**2).sum(axis=1)
    U = -((A[:,0]-C[...,0])*T[:,0] + (A[:,1]-C[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = A + U*T - C
    return np.sqrt((D**2).sum(axis=1))

A = np.random.uniform(-10,10,(10,2))
B = np.random.uniform(-10,10,(10,2))
C  = np.random.uniform(-10,10,( 1,2))
print(distance(A, B, C))

[1.65904067 3.28088071 0.90985701 3.43263335 5.5268526  8.93080812
 5.15218387 7.42140223 8.86152718 2.29286068]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
X = np.random.uniform(-10, 10, (10,2))
Y = np.random.uniform(-10,10,(10,2))
Z = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(X,Y,Z_i) for Z_i in Z]))

[[ 3.7828541   3.04184089 11.16486967  2.54973078 11.43450173  0.52022947
   7.38636127 10.1802215   2.04086212  0.18009952]
 [ 6.02824233  1.45656817  5.40883142  0.63980016  4.80317347 15.14347093
  12.44406009  3.36567361 14.6018833   1.39162838]
 [12.27852569 10.52290757 17.7846449   2.76022602 16.08841901  8.31946159
   0.23935593  7.16486878  6.54665227  5.26717126]
 [10.9937371   8.96182511 17.71014843  1.12264401 16.51193981  7.83081239
   1.30289685  8.68942564  5.52234133  3.62746434]
 [12.31967997 11.58379578 15.60732467  4.77587994 13.42297222  6.71005964
   1.20388811  4.60241843  5.93405235  7.23904312]
 [ 8.24369338 10.51340521  7.00017067  7.12000949  4.58246687  1.08093926
   0.174489    0.21407075  0.20583388  9.40803196]
 [ 2.59520159  4.2702272   9.85150196  9.82932838 12.38903971  2.60901359
  14.64640275 16.6604671   7.40521648  7.48922754]
 [ 6.31705683 10.85297701  1.10859171  9.87009198  1.81434864  6.12281577
   0.06058589  4.5931676   3.04161393 12.03865183]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[5 8 4 5 7 5 5 5 8 6]
 [5 3 7 1 1 4 8 6 8 5]
 [7 5 4 1 5 7 2 2 1 6]
 [2 4 8 9 1 4 0 2 0 0]
 [3 9 3 3 5 5 3 1 9 1]
 [0 8 8 2 4 9 3 6 1 4]
 [1 2 0 9 5 9 6 8 1 4]
 [1 6 6 2 2 5 9 5 9 0]
 [7 4 7 8 4 5 2 3 5 3]
 [1 0 6 6 6 2 6 4 4 6]]
[[0 0 0 0 0]
 [0 5 8 4 5]
 [0 5 3 7 1]
 [0 7 5 4 1]
 [0 2 4 8 9]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
A = np.arange(1,15,dtype=np.uint32)
B = stride_tricks.as_strided(A,(11,4),(4,4))
print(B)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
N = np.random.randint(0,10,50)
print(np.bincount(N).argmax())

1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
N = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (N.shape[0]-3)
j = 1 + (N.shape[1]-3)
Z = stride_tricks.as_strided(N, shape=(i, j, n, n), strides=N.strides + N.strides)
print(Z)

[[[[0 1 1]
   [2 2 4]
   [4 0 0]]

  [[1 1 3]
   [2 4 3]
   [0 0 2]]

  [[1 3 2]
   [4 3 1]
   [0 2 1]]

  [[3 2 1]
   [3 1 2]
   [2 1 4]]

  [[2 1 0]
   [1 2 0]
   [1 4 1]]

  [[1 0 2]
   [2 0 1]
   [4 1 0]]

  [[0 2 3]
   [0 1 4]
   [1 0 0]]

  [[2 3 0]
   [1 4 1]
   [0 0 0]]]


 [[[2 2 4]
   [4 0 0]
   [3 0 4]]

  [[2 4 3]
   [0 0 2]
   [0 4 0]]

  [[4 3 1]
   [0 2 1]
   [4 0 3]]

  [[3 1 2]
   [2 1 4]
   [0 3 1]]

  [[1 2 0]
   [1 4 1]
   [3 1 3]]

  [[2 0 1]
   [4 1 0]
   [1 3 4]]

  [[0 1 4]
   [1 0 0]
   [3 4 4]]

  [[1 4 1]
   [0 0 0]
   [4 4 4]]]


 [[[4 0 0]
   [3 0 4]
   [2 3 2]]

  [[0 0 2]
   [0 4 0]
   [3 2 2]]

  [[0 2 1]
   [4 0 3]
   [2 2 1]]

  [[2 1 4]
   [0 3 1]
   [2 1 3]]

  [[1 4 1]
   [3 1 3]
   [1 3 3]]

  [[4 1 0]
   [1 3 4]
   [3 3 3]]

  [[1 0 0]
   [3 4 4]
   [3 3 0]]

  [[0 0 0]
   [4 4 4]
   [3 0 4]]]


 [[[3 0 4]
   [2 3 2]
   [2 2 3]]

  [[0 4 0]
   [3 2 2]
   [2 3 1]]

  [[4 0 3]
   [2 2 1]
   [3 1 4]]

  [[0 3 1]
   [2 1 3]
   [1 4 3]]

  [[3 1 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

N = symetric(np.random.randint(0,10,(5,5)))
N[2,3] = 42
print(N)

[[ 6  7  4 13 11]
 [ 7  7 14  8  4]
 [ 4 14  0 42 11]
 [13  8 42  2 12]
 [11  4 11 12  1]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
A = np.ones((16,16))
B = 4
C = np.add.reduceat(np.add.reduceat(A, np.arange(0, A.shape[0], B), axis=0),
                                       np.arange(0, A.shape[1], B), axis=1)
print(C)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9997 9996 9999 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
X = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
Y = np.core.records.fromarrays(X.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(Y)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
A = np.random.rand(5e7)

%timeit np.power(A,3)
%timeit A*A*A
%timeit np.einsum('i,i,i->i',A,A,A)

TypeError: ignored

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 3 4 5]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
N = np.random.randint(0,5,(10,3))
print(N)
A = np.all(N[:,1:] == N[:,:-1], axis=1)
B = N[~A]
print(B)
B = N[N.max(axis=1) != N.min(axis=1),:]
print(B)

[[4 3 3]
 [0 0 2]
 [3 4 1]
 [0 0 0]
 [1 0 0]
 [3 2 4]
 [2 4 4]
 [3 2 4]
 [0 2 1]
 [3 4 1]]
[[4 3 3]
 [0 0 2]
 [3 4 1]
 [1 0 0]
 [3 2 4]
 [2 4 4]
 [3 2 4]
 [0 2 1]
 [3 4 1]]
[[4 3 3]
 [0 0 2]
 [3 4 1]
 [1 0 0]
 [3 2 4]
 [2 4 4]
 [3 2 4]
 [0 2 1]
 [3 4 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
A = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((A.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
A = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(A[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
X = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(X).view(np.dtype((np.void, X.dtype.itemsize * X.shape[1])))
_, idx = np.unique(T, return_index=True)
a = X[idx]
print(a)
a = np.unique(X, axis=0)
print(a)

[[0 0 1]
 [0 1 1]
 [1 1 0]
 [1 1 1]]
[[0 0 1]
 [0 1 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.76146904, 0.9445571 , 0.44209016, 0.2668975 , 0.07722725,
        0.03781141, 0.25705413, 0.96384155, 0.16895717, 0.23813721],
       [0.73185554, 0.90782332, 0.42489729, 0.25651787, 0.07422389,
        0.03634092, 0.24705731, 0.92635779, 0.16238643, 0.22887607],
       [0.67442524, 0.83658444, 0.39155468, 0.23638835, 0.06839938,
        0.03348917, 0.22767018, 0.85366448, 0.14964362, 0.21091566],
       [0.68039438, 0.8439888 , 0.39502021, 0.23848056, 0.06900476,
        0.03378557, 0.22968522, 0.86122001, 0.15096807, 0.21278241],
       [0.45457778, 0.56387672, 0.26391666, 0.15933107, 0.04610272,
        0.02257245, 0.15345482, 0.57538905, 0.10086316, 0.1421619 ],
       [0.25298122, 0.31380818, 0.14687467, 0.08867078, 0.02565704,
        0.012562  , 0.08540054, 0.32021501, 0.05613228, 0.07911581],
       [0.03676087, 0.04559968, 0.02134246, 0.01288481, 0.00372824,
        0.00182539, 0.01240961, 0.04653066, 0.00815662, 0.01149637],
       [0.59099435, 0.73309338, 0.3431167

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
A = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
x = 4
y = np.logical_and.reduce(np.mod(A, 1) == 0, axis=-1)
y &= (A.sum(axis=-1) == x)
print(A[y])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
a = np.random.randn(100) # random 1D array
b = 1000 # number of bootstrap samples
idx = np.random.randint(0, a.size, (b, a.size))
X = a[idx].mean(axis=1)
Y = np.percentile(X, [2.5, 97.5])
print(Y)

[-0.16624187  0.27174028]
